# Generated by Django 5.2.7 on 2025-10-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customerreport',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerreport',
            name='phone',
        ),
    ]
