# Generated by Django 5.2.4 on 2025-10-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerreport', '0002_alter_customerreport_options_and_more'),
        ('product', '0003_alter_product_description_alter_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreport',
            name='products',
            field=models.ManyToManyField(related_name='customer_reports', to='product.product'),
        ),
    ]
