# Generated by Django 5.2.4 on 2025-11-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('receipt_upload', 'Receipt Upload'), ('bank_transfer', 'Bank Transfer'), ('pos', 'POS'), ('other', 'Other')], default='cash', max_length=20)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload receipt file for receipt_upload payment method', null=True, upload_to='receipts/')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
        ),
    ]
