# Generated by Django 5.2.6 on 2025-10-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('receipt_upload', 'Receipt Upload'), ('bank_transfer', 'Bank Transfer'), ('pos', 'POS'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
