# Generated by Django 5.2.6 on 2025-10-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload receipt file for receipt_upload payment method', null=True, upload_to='receipts/'),
        ),
    ]
