# Generated by Django 5.2.4 on 2025-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FRUIT', 'Fruit'), ('DRINKS', 'Drinks'), ('GRAIN', 'Grain'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine'), ('COSMETICS', 'Cosmetics'), ('STATIONERY', 'Stationery')], default='ELECTRONICS', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('max_stock_level', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('is_perishable', models.BooleanField(default=False)),
                ('reorder_point', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
