# Generated by Django 5.2.4 on 2025-10-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('FRUIT', 'Fruit'), ('DRINKS', 'Drinks'), ('GRAIN', 'Grain'), ('FOOD', 'food')], default='ELECTRONICS', max_length=20),
        ),
    ]
