# Generated by Django 5.2.4 on 2025-11-19 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier name', max_length=255)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer')], default='company', max_length=20)),
                ('email', models.EmailField(help_text='Supplier email', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(help_text='Full address')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Legal company name', max_length=255, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=255, null=True)),
                ('contact_position', models.CharField(blank=True, help_text="Contact person's position", max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about supplier', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
