# Generated by Django 5.2.6 on 2025-10-26 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(help_text='Full address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, help_text='Legal company name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact person', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_position',
            field=models.CharField(blank=True, help_text="Contact person's position", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='Supplier email', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Supplier name', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about supplier', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax identification number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_su_name_3342d4_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['email'], name='supplier_su_email_5f5ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='supplier_su_status_5b9f42_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['type'], name='supplier_su_type_98b590_idx'),
        ),
    ]
